/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import LeadOutListRunTime from "./runtimes/LeadOutListRunTime"
import FLBoxDialogManage from "./manages/dialogManage/FLBoxDialogManage"
import FreeSkinOfStartDialogManage from "./manages/dialogManage/FreeSkinOfStartDialogManage"
import DialogBgRunTime from "./runtimes/DialogBgRunTime"
import AwardDialogManage from "./manages/dialogManage/AwardDialogManage"
import LeadOutGridRunTime from "./runtimes/LeadOutGridRunTime"
import GameFinishDialogManage from "./manages/dialogManage/GameFinishDialogManage"
import GameOverDialogManage from "./manages/dialogManage/GameOverDialogManage"
import ShopManage from "./manages/dialogManage/ShopManage"
import GetCoinTimtsDialogManage from "./manages/dialogManage/GetCoinTimtsDialogManage"
import MuneDialogManage from "./manages/dialogManage/MuneDialogManage"
import LeadOutGrid2RunTime from "./runtimes/LeadOutGrid2RunTime"
import OthersGameDialog from "./manages/dialogManage/OthersGameDialog"
import PauseDialogManage from "./manages/dialogManage/PauseDialogManage"
import RankDiaogManage from "./manages/dialogManage/RankDiaogManage"
import SignManage from "./manages/dialogManage/SignManage"
import SkinFreeDialogManage from "./manages/dialogManage/SkinFreeDialogManage"
import StartDialogManage from "./manages/dialogManage/StartDialogManage"
import GameManage from "./manages/GameManage"
import Loading from "./manages/Loading"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="center";
    static startScene:any="scene/game/loading.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("runtimes/LeadOutListRunTime.ts",LeadOutListRunTime);
        reg("manages/dialogManage/FLBoxDialogManage.ts",FLBoxDialogManage);
        reg("manages/dialogManage/FreeSkinOfStartDialogManage.ts",FreeSkinOfStartDialogManage);
        reg("runtimes/DialogBgRunTime.ts",DialogBgRunTime);
        reg("manages/dialogManage/AwardDialogManage.ts",AwardDialogManage);
        reg("runtimes/LeadOutGridRunTime.ts",LeadOutGridRunTime);
        reg("manages/dialogManage/GameFinishDialogManage.ts",GameFinishDialogManage);
        reg("manages/dialogManage/GameOverDialogManage.ts",GameOverDialogManage);
        reg("manages/dialogManage/ShopManage.ts",ShopManage);
        reg("manages/dialogManage/GetCoinTimtsDialogManage.ts",GetCoinTimtsDialogManage);
        reg("manages/dialogManage/MuneDialogManage.ts",MuneDialogManage);
        reg("runtimes/LeadOutGrid2RunTime.ts",LeadOutGrid2RunTime);
        reg("manages/dialogManage/OthersGameDialog.ts",OthersGameDialog);
        reg("manages/dialogManage/PauseDialogManage.ts",PauseDialogManage);
        reg("manages/dialogManage/RankDiaogManage.ts",RankDiaogManage);
        reg("manages/dialogManage/SignManage.ts",SignManage);
        reg("manages/dialogManage/SkinFreeDialogManage.ts",SkinFreeDialogManage);
        reg("manages/dialogManage/StartDialogManage.ts",StartDialogManage);
        reg("manages/GameManage.ts",GameManage);
        reg("manages/Loading.ts",Loading);
    }
}
GameConfig.init();